ItransitionTask5/Models/Message.cs
using System.ComponentModel.DataAnnotations;
using ItransitionTask5.Tools;

namespace ItransitionTask5.Models;

[Serializable]
public class Message
{
    [Key] public int Id { get; set; }

    public string From { get; set; } = null!;

    public string To { get; set; } = null!;

    public int? ReplyFor { get; set; }

    public string Title { get; set; } = null!;

    public string Text { get; set; } = null!;

    public string DateTime { get; set; } = null!;

    public static bool Validate(Message? message)
    {
        return message != null && !StringTools.StringEmpty(
            message.From, message.To, message.Text, message.Title);
    }
}

ItransitionTask5/Models/MessagesContext.cs
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace ItransitionTask5.Models;

public class MessagesContext : DbContext
{
    public DbSet<Message> Messages { get; set; }

    public MessagesContext(DbContextOptions<MessagesContext> options) : base(options)
    {
        Database.EnsureCreated();
    }

    public Message InitMessage(Message message)
    {
        message.DateTime = DateTime.Now.ToString();
        return message;
    }

    public List<Message> GetMessagesWithName(string name)
    {
        Debug.WriteLine("Start search messages with " + name);
        List<Message> messagesList = Messages.Where(message => message.From == name || message.To == name).ToList();
        Debug.WriteLine("Found " + messagesList.Count() + " messages for " + name);
        return messagesList;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("Host=localhost;Port=5432;Database=task5;Username=postgres;Password=174285396020");
    }
}

ItransitionTask5/Models/NameModel.cs
using System.ComponentModel.DataAnnotations;

namespace ItransitionTask5.Models;

[Serializable]
public class NameModel
{
    [Key] public int Id { get; set; }

    public string Name { get; set; } = null!;
}

ItransitionTask5/Models/NamesContext.cs
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace ItransitionTask5.Models;

public class NamesContext : DbContext
{
    public DbSet<NameModel> Names { get; set; }

    public NamesContext(DbContextOptions<NamesContext> options) : base(options)
    {
        Database.EnsureCreated();
    }

    public async void TryAddName(string name)
    {
        if (await Names.FirstOrDefaultAsync(n => n.Name == name) == null)
        {
            Names.Add(new NameModel() {Name = name});
            await SaveChangesAsync();
        }
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("Host=localhost;Port=5432;Database=task5;Username=postgres;Password=174285396020");
    }
}

ItransitionTask5/ViewModels/ErrorViewModel.cs
namespace ItransitionTask5.ViewModels;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ItransitionTask5/ViewModels/HomeViewModel.cs
using ItransitionTask5.Models;

namespace ItransitionTask5.ViewModels;

public class HomeViewModel
{
    public string Name { get; set; } = null!;
    public string HostUrl { get; set; } = null!;
    public NamesContext NamesContext { get; set; } = null!;
}

ItransitionTask5/ViewModels/SendMessageViewModel.cs
using ItransitionTask5.Models;

namespace ItransitionTask5.ViewModels;

public class SendMessageViewModel
{
    public string Name { get; set; } = null!;
    public List<NameModel> PossibleNames { get; set; } = null!;
}

ItransitionTask5/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ItransitionTask5.Models;
using ItransitionTask5.Services;
using ItransitionTask5.ViewModels;

namespace ItransitionTask5.Controllers;

public class HomeController : Controller
{
    private readonly IHostInfo hostInfo;
    private readonly NamesContext namesContext;

    public HomeController(IHostInfo hostInfo, NamesContext namesContext)
    {
        this.hostInfo = hostInfo;
        this.namesContext = namesContext;
    }

    public IActionResult Index()
    {
        if (!Request.Cookies.ContainsKey("Name"))
        {
            Debug.WriteLine("Redirect to login");
            return RedirectToAction("Index", "Login");
        }
        return View(new HomeViewModel() {Name = Request.Cookies["Name"]!, HostUrl = hostInfo.GetHostUrl(),
            NamesContext = namesContext
        });
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

ItransitionTask5/Controllers/LoginController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace ItransitionTask5.Controllers;

public class LoginController : Controller
{
    [HttpGet]
    public IActionResult Index()
    {
        if (CheckNameCookie())
            return RedirectToAction("Index", "Home");
        return View();
    }

    [HttpGet]
    public IActionResult ChangeName()
    {
        ClearCookies();
        return RedirectToAction("Index", "Login");
    }

    [HttpPost]
    public IActionResult Login()
    {
        string name = Request.Form["Name"];
        if (!string.IsNullOrEmpty(name) && !string.IsNullOrWhiteSpace(name))
        {
            ConfigureCookies(name);
            return RedirectToAction("Index", "Home");
        }

        return Index();
    }

    private bool CheckNameCookie()
    {
        return Request.Cookies.ContainsKey("Name");
    }

    private void ClearCookies()
    {
        Response.Cookies.Delete("Name");
    }

    private void ConfigureCookies(string name)
    {
        ClearCookies();
        DateTime expires = DateTime.Now.AddYears(1);
        CookieOptions options = new CookieOptions();
        options.Expires = expires;
        Response.Cookies.Append("Name", name, options);
    }
}

ItransitionTask5/ViewComponents/MessageViewViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ItransitionTask5.ViewComponents;

[ViewComponent]
public class MessageViewViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View();
    }
}

ItransitionTask5/ViewComponents/MessagesListViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ItransitionTask5.ViewComponents;

[ViewComponent]
public class MessagesListViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View();
    }
}

ItransitionTask5/ViewComponents/SendMessageViewComponent.cs
using ItransitionTask5.Models;
using ItransitionTask5.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ItransitionTask5.ViewComponents;

[ViewComponent]
public class SendMessageViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(NamesContext namesContext)
    {
        return View(new SendMessageViewModel() {Name = Request.Cookies["Name"]!, 
            PossibleNames = namesContext.Names.ToList()});
    }
}

ItransitionTask5/Views/Home/Index.cshtml
@model ItransitionTask5.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home";
}

<div>

    @await Component.InvokeAsync("MessagesList")

    @await Component.InvokeAsync("MessageView")

    @await Component.InvokeAsync("SendMessage", Model.NamesContext)
</div>

<script>
    var socket;
    var messagesData = [];
    var toast = document.getElementById("toast");
    
    window.onload = () => {
        establishSocketConnection();
    }
    
    var onMessageSelect = () => {
        hideList(true);
        hideWatch(false);
        
    }
        
    var openMessagesList = () => {
        hideList(false);
        hideWatch(true);
        hideSend(true);
    }
        
    var openSendMessage = () => {
        hideList(true);
        hideWatch(true);
        hideSend(false);
    }
    
    function getList() {
        return document.getElementById("MessagesListView");
    }
    function getWatch() {
        return document.getElementById("MessageView");
    }
    function getSend() {
        return document.getElementById("SendMessageView");
    }
    
    function hideWatch(hide) {
        getWatch().hidden = hide;
    }
    function hideList(hide) {
        getList().hidden = hide;
    }
    function hideSend(hide) {
        getSend().hidden = hide;
    }
    
    function establishSocketConnection(){
        console.log("Establishing connection");
        socket = new WebSocket("@Model.HostUrl");
        socket.addEventListener("open", function onSocketMessage(event)
        {
            console.log("Connection opened");
            sendData("@Model.Name");
        });
        socket.addEventListener("close", function onSocketMessage(event)
        {
            console.log("Connection cloase");
        });
        socket.addEventListener("error", function onSocketMessage(event)
        {
            console.error('Error! ', event.data);
        });
        socket.addEventListener("message", function onSocketMessage(event)
        {
            console.log('Message from server ', event.data);
            if (event.data.toString().includes("Id")) {
                addMessageToList(event.data);
            }
        });
    }
    
    function sendData(data) {
        console.log("Sending data", JSON.stringify(data));
        socket.send(JSON.stringify(data));
    }
    
    function addMessageToList(stringData) {
        var data = JSON.parse(stringData);
        messagesData.push(data);
        var content = document.getElementById("MessagesListContent");
        var prefab = document.getElementById("prefab");
        var clone = prefab.cloneNode(true);
        clone.hidden = false;
        var i = messagesData.length - 1;
        clone.addEventListener('click', function(){
                 showMessage(i);
             });
        clone.removeAttribute("id");
        content.insertBefore(clone, content.firstChild);
        var title = clone.querySelector(".mb-1");
        title.innerText = data.Title;
        var time = clone.querySelector(".time");
        if (data.DateTime == null)
            data.DateTime = new Date().toString();
        time.innerText = getCurrentDateTimeDifference(new Date(data.DateTime));
        var fromto = clone.querySelector(".fromto");
        fromto.innerText = "From " + data.From + " to " + data.To;
    }
    
    function getCurrentDateTimeDifference(dateTime) {
        var m1 = new Date().getTime();
        var m2 = dateTime.getTime();
        var diff = m1 - m2;
        var ans = "";
        var days = Math.floor(diff / 86400000);
        if (days!=0)
            ans += days + " days ";
        diff-=days * 86400000;
        var hours = Math.floor(diff / 3600000);
        if (hours!=0)
            ans += hours + " hours ";
        diff-=hours * 3600000;
        var minutes = Math.floor(diff / 60000);
        ans += minutes + " minutes ago";
        return ans;
    }
</script>

ItransitionTask5/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Enter your name";
    Layout = "_Layout";
}

<form asp-controller="Login" asp-action="Login">
    <div class="form-outline mb-4">
        <label class="form-label" for="name">Name</label>
        <input name="Name" oninput="onNameChanged(event)" type="text" id="name" class="form-control" 
               placeholder="Type here"/>
    </div>
    <button id="submitBtn" type="submit" class="btn btn-primary btn-block" hidden="hidden">Login as </button>
</form>

<script>
    var onNameChanged = event => {
        var submitBtn = document.getElementById("submitBtn");
        var input = document.getElementById("name");
        submitBtn.innerText = "Login as " + input.value;
        if (input.value == "")
            submitBtn.hidden = true;
        else
            submitBtn.hidden = false;
    }
    
</script>

ItransitionTask5/Views/Shared/Components/MessageView/Default.cshtml
<div id="MessageView" class="" hidden="hidden">
    <div>
        <button class="btn-danger rounded" onclick="openMessagesList()">Back</button>
    </div>
    <br/>
    <div class="d-flex w-100 justify-content-between">
        <h5 id="messageViewTitle" class="mb-1">List group item heading</h5>
        <small id="messageViewTime">3 days ago</small>
    </div>
    <small id="messageViewFromto"></small>
    <p id="messageViewText"></p>
</div>

<script>
    title = document.getElementById("messageViewTitle");
    text = document.getElementById("messageViewText");
    time = document.getElementById("messageViewTime");
    fromto = document.getElementById("messageViewFromto");
    function showMessage(i) {
        title.innerText = messagesData[i].Title;
        var div = document.createElement( 'div' );
        div.innerHTML = marked.parse(messagesData[i].Text);
        try{
        text.removeChild(text.firstChild);
        } catch {}
        text.appendChild(div);
        time.innerText = messagesData[i].DateTime;
        fromto.innerText = "From " + messagesData[i].From + " To " + messagesData[i].To;
        onMessageSelect();
    }
</script>

ItransitionTask5/Views/Shared/Components/MessagesList/Default.cshtml
<div id="MessagesListView">
    <h2>@Model.Name meassages</h2>
    <div>
        <button onclick="openSendMessage()" class="btn-primary rounded">Send message</button>
    </div>
    <br/>
    <div id="MessagesListContent" class="list-group">
        <a id="prefab" hidden="hidden" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">List group item heading</h5>
                <small class="time">3 days ago</small>
            </div>
            <small class="fromto">Donec id elit non mi porta.</small>
        </a>
    </div>
</div>

ItransitionTask5/Views/Shared/Components/SendMessage/Default.cshtml
@model ItransitionTask5.ViewModels.SendMessageViewModel

<div id="SendMessageView" class="" hidden="hidden">
    <h2>Send message</h2>
    <div>
        <button class="btn-danger rounded" onclick="openMessagesList()">Back</button>
        <button class="btn-primary rounded" onclick="sendMessage()">Send</button>
    </div>
    <br/>
    <form>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Title</span>
            </div>
            <input name="Title" type="text" class="form-control" placeholder="Type title here" aria-label="Title"
                   aria-describedby="basic-addon1">
        </div>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Message</span>
            </div>
            <textarea name="Text" class="form-control" aria-label="Message" 
placeholder="Type your message here"></textarea>
        </div>
        <h3>Recipients</h3>
        <div id="recipientsParent" class="list-group">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">Recipient</span>
                </div>
                <input list="namesList" name="To" type="text" class="form-control" placeholder="Type recipient name"
                       aria-label="Recipient"
                       aria-describedby="basic-addon1">
            </div>
            <datalist id="namesList">
                @foreach (NameModel nameModel in Model.PossibleNames)
                {
                    <option>@nameModel.Name</option>
                }
            </datalist>
        </div>
    </form>

    <div>
        <button class="btn-light rounded" onclick="addRecipient()">Add recipient</button>
        <button class="btn-light rounded" onclick="removeRecipient()">Remove recipient</button>
    </div>
</div>

<script>
    var recipientCount = 1;
    var id = 0;
    function addRecipient() {
        let element = document.createElement('div')
        element.class="input-group mb-3";
        element.innerHTML = "<div class='input-group mb-3'>" +
                            "<div class='input-group-prepend'>" +
                            "<span class='input-group-text' id='basic-addon1'>Recipient</span>" +
                            "</div>" +
                            "<input list='namesList' name='To' type='text' class='form-control' placeholder='Type recipient name'" +
                            "aria-label='Recipient'" +
                            "aria-describedby='basic-addon1'>" +
                            "</div>"
        document.getElementById('recipientsParent').appendChild(element);
    }
    function removeRecipient() {
        var element = document.getElementById("recipientsParent");
        if (element.childNodes.length>2)
            element.removeChild(element.lastChild);
    }
    
    function sendMessage() {
        var recipients = [];
        for (var element of document.getElementsByName("To"))
            recipients.push(element.value);
        let data = {
            Title: document.getElementsByName("Title")[0].value,
            Text: document.getElementsByName("Text")[0].value,
            From: "@Model.Name",
            To: recipients
        }
        var recipientsFilled = true;
        for (let res of recipients)
            if (res == "")
                {
                    recipientsFilled = false;
                    break;
                }
        if (!data.From || !recipientsFilled || !data.Text || !data.Title)
            alert("You leaved some fields empty!");
        else
        {
            sendData(data);
            openMessagesList();
            for (var recipient of recipients)
            {
                let msgData = {
                Title: document.getElementsByName("Title")[0].value,
                Text: document.getElementsByName("Text")[0].value,
                From: "@Model.Name",
                To: recipient
                }
                addMessageToList(JSON.stringify(msgData));
            }
        }
    }
</script>

ItransitionTask5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body id="body">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="https://github.com/godsended?tab=repositories">ItransitionTask5</a>
            <a class="nav-item" asp-action="ChangeName" asp-controller="Login">Change name</a>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/marked@4.0.16/lib/marked.umd.min.js"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>